## About

A diligent and result-driven professional with over 10 years in Telecoms Engineering, Operations,
and RF Planning & Optimization. A manager with strong work ethics matched with consistent
track record of excellent performance. Analytical with strong people and multi Vendor management skills.
Outstanding record of executing mission-critical projects and initiatives on schedule and
within budget. Excellent Analytical and communication skills to convey complex concepts, with proven ability
to build and lead highly efficient teams. Currently coordinating RF Planning and Optimization as
Manager in a leading Telco in Nigeria. Also experienced in Pre-sales Planning, Project Management, and Managed Services Operations.

## Interests

** Big Data Anaysis with key interest in 
* Technology
* Medecine
* Finance
* National Development

## Projects

* 1. Technology - GUL

    Ensure balancing of traffic between different technologies
    Ensure the selected UTRAN & eUTRAN solutions are capacity future prove
    Minimize the HR utilization 

* 2.Design & Monitor UTRAN and eUTRAN Interfaces -

    Design the UTRAN and eUTRAN interfaces based on traffic forecast

    Monitor the traffic gross and ensure to keep system in good utilization

    Recommend cost effective solutions

* 3. Capacity Planning -

    Follow up with core network and transport Engineering to ensure end to end capacity planning
    Ensure the utilization of LTE and 3G layer in efficient way
    Understanding the HW and SW capabilities of the telecom equipment(Multi Vendor requirements)
    Capacity plan for special events and sudden traffic increase 

## Profiles 

* [LinkedIn](https://www.linkedin.com/in/engr-moses-maor)
* [Facebook](http://facebook.com/mosedoo)
* [twitter](http://twitter.com@MosesMaor)
* [GitHub](http://github.com/Moses-Maor)

## Contact

* [moses.maor@email](mailto:moses.maor@email)